# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  surbana-pg:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - postgres-password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=surbana
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - public
volumes:
  postgres-data:
secrets:
  postgres-password:
    file: postgres-data/password.txt
networks:
  public:
    driver: bridge
